// Code generated by tool. DO NOT EDIT.
// app: htr, biz: common

package errno

import (
	"github.com/crazyfrankie/frx/errorx/code"
)

const (
	ErrInternalServerCode              = 100101
	errInternalServerMessage           = "internal server error"
	errInternalServerNoAffectStability = true

	ErrInvalidParamsCode              = 100102
	errInvalidParamsMessage           = "invalid params"
	errInvalidParamsNoAffectStability = true

	ErrAuthenticationCode              = 100103
	errAuthenticationMessage           = "authentication failed"
	errAuthenticationNoAffectStability = true

	ErrNoPermissionCode              = 100104
	errNoPermissionMessage           = "no access permission"
	errNoPermissionNoAffectStability = true

	ErrTokenExpiredCode              = 100105
	errTokenExpiredMessage           = "token is expired"
	errTokenExpiredNoAffectStability = true

	ErrTokenInvalidCode              = 100106
	errTokenInvalidMessage           = "token is invalid"
	errTokenInvalidNoAffectStability = true

	ErrTokenMalformedCode              = 100107
	errTokenMalformedMessage           = "token is malformed"
	errTokenMalformedNoAffectStability = true

	ErrTokenNotValidYetCode              = 100108
	errTokenNotValidYetMessage           = "token is not valid yet"
	errTokenNotValidYetNoAffectStability = true
)

func init() {

	code.Register(
		ErrInternalServerCode,
		errInternalServerMessage,
		code.WithAffectStability(!errInternalServerNoAffectStability),
	)

	code.Register(
		ErrInvalidParamsCode,
		errInvalidParamsMessage,
		code.WithAffectStability(!errInvalidParamsNoAffectStability),
	)

	code.Register(
		ErrAuthenticationCode,
		errAuthenticationMessage,
		code.WithAffectStability(!errAuthenticationNoAffectStability),
	)

	code.Register(
		ErrNoPermissionCode,
		errNoPermissionMessage,
		code.WithAffectStability(!errNoPermissionNoAffectStability),
	)

	code.Register(
		ErrTokenExpiredCode,
		errTokenExpiredMessage,
		code.WithAffectStability(!errTokenExpiredNoAffectStability),
	)

	code.Register(
		ErrTokenInvalidCode,
		errTokenInvalidMessage,
		code.WithAffectStability(!errTokenInvalidNoAffectStability),
	)

	code.Register(
		ErrTokenMalformedCode,
		errTokenMalformedMessage,
		code.WithAffectStability(!errTokenMalformedNoAffectStability),
	)

	code.Register(
		ErrTokenNotValidYetCode,
		errTokenNotValidYetMessage,
		code.WithAffectStability(!errTokenNotValidYetNoAffectStability),
	)

}
