// Code generated by tool. DO NOT EDIT.
// app: htr, biz: common

package errno

import (
	"github.com/crazyfrankie/frx/errorx/code"
)

const (
	ErrInvalidParamsCode              = 100101
	errInvalidParamsMessage           = "invalid params"
	errInvalidParamsNoAffectStability = true
)

func init() {

	code.Register(
		ErrInvalidParamsCode,
		errInvalidParamsMessage,
		code.WithAffectStability(!errInvalidParamsNoAffectStability),
	)

}
